### PR TITLE
Fixed Tysha issue

### LINKED ISSUE #436: Tysha's page is messed up
Check out https://www.got.show/characters/Tysha

no PLOD, no death date, no profile pic, no name

### PR DESCRIPTION
**Pull request by yashha**
Closes #436

### CODE REVIEW

File: app/components/public/Characters/Characters.jsx [hunk 1]
```diff
@@ -47,15 +47,13 @@ export default class Character extends Component {
...
-            sentiment: SentimentStore.getCharacterSentiment()
-        });
 
         const check = !character.dateOfDeath && character.gotplod && character.gotarffplod;
         this.setState({
             plod: (check) ? parseInt(character.gotplod.plod) || 0 : 100,
-            plodText: (check) ? '%(percent)s%' : 'D E A D'
+            plodText: (check) ? '%(percent)s%' : 'D E A D',
+            character: character,
+            sentiment: SentimentStore.getCharacterSentiment() | { positive: 0, negative: 0}
```
Comment (sacdallago) [inline app/components/public/Characters/Characters.jsx:56]: @yashha this is the suspicious line

**Comment by sacdallago** [comment]
So this is the faulty code to be fixed @yashha please :)

**Comment by yashha** [comment]
Ok I check it :)
